name: Comment on CRs in PR

on:
  pull_request:
    branches: [main]

# CR mbarbin: Currently failing due to lack of read access. Will try with the
# read permission set explicitly.
permissions:
  contents: read
  pull-requests: write

jobs:
  comment-crs-in-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install crs
        uses: ./setup-crs
        with:
          crs_version: 0.0.20250626
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
      - name: Comment on CRs in PR
        uses: ./comment-crs-in-pr
        with:
          crs_config: .github/crs-config.json
