name: Comment on CRs in PR

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  comment-crs-in-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install crs
        uses: ./setup-crs
        with:
          crs-version: 0.0.20250705
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
      - name: Comment on CRs in PR
        uses: ./comment-crs-in-pr
        with:
          crs-config: .github/crs-config.json
